CREATE TABLE [dbo].[tblRecurringItem] (
    [rciID]               INT              IDENTITY (1, 1) NOT NULL,
    [rciName]             VARCHAR (300)    NOT NULL,
    [rciDescription]      VARCHAR (300)    NULL,
    [rciCategory_lvlID]   INT              NULL,
    [rciMinimumDue]       MONEY            NULL,
    [rciBalance]          MONEY            NULL,
    [rciInterestRate]     FLOAT (53)       NULL,
    [rciDay]              INT              NOT NULL,
    [rciJan]              BIT              NULL,
    [rciFeb]              BIT              NULL,
    [rciMar]              BIT              NULL,
    [rciApr]              BIT              NULL,
    [rciMay]              BIT              NULL,
    [rciJun]              BIT              NULL,
    [rciJul]              BIT              NULL,
    [rciAug]              BIT              NULL,
    [rciSep]              BIT              NULL,
    [rciOct]              BIT              NULL,
    [rciNov]              BIT              NULL,
    [rciDec]              BIT              NULL,
    [rciPaidOff]          BIT              NULL,
    [rciDateCreated]      DATETIME         CONSTRAINT [DF_tblRecurringItem_rciDateCreated] DEFAULT ([dbo].[fncGetLocalDateTime]()) NULL,
    [rciCreatedBy_prnID]  INT              NULL,
    [rciDateModified]     DATETIME         NULL,
    [rciModifiedBy_prnID] INT              NULL,
    [rciGUID]             UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    PRIMARY KEY CLUSTERED ([rciID] ASC),
    CONSTRAINT [fk_tblrecurringItem_rciCategory_lvlID_tblLookupValue] FOREIGN KEY ([rciCategory_lvlID]) REFERENCES [dbo].[tblLookupValue] ([lvlID]),
    CONSTRAINT [fk_tblRecurringItem_rciCreatedBy_prnID_tblPerson] FOREIGN KEY ([rciCreatedBy_prnID]) REFERENCES [dbo].[tblPerson] ([prnID]),
    CONSTRAINT [fk_tblRecurringItem_rciModifiedBy_prnID_tblPerson] FOREIGN KEY ([rciModifiedBy_prnID]) REFERENCES [dbo].[tblPerson] ([prnID])
);

